version: '3.9'

services:
  db:
    image: mariadb:latest    
    restart: always    
    ports:
       - 3306:3306
    environment:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: pfs
          MYSQL_USER: user
          MYSQL_PASSWORD: user    
    volumes:      - ./init:/docker-entrypoint-initdb.d